# Generated by Django 5.2.4 on 2025-07-23 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('REC', 'Records'), ('CLO', 'Clothing'), ('POS', 'Posters'), ('MISC', 'Miscellaneous')], default=2025, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='year',
            field=models.IntegerField(default=2024, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
            preserve_default=False,
        ),
    ]
