# Generated by Django 5.2.4 on 2025-07-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_article_description_article_sold_article_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='article',
            name='type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='year',
        ),
    ]
