# Generated by Django 5.2.4 on 2025-07-26 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_article_description_article_sold_article_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='band',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='listings.band'),
        ),
    ]
